POST http://127.0.0.1:1337/api/v1/user/register 
Content-Type: application/json

{
   "first_name": "Aleks_4",
   "last_name": "Star",
   "email": "test@mail.ru",
   "password": "5aaaaaaaa",
   "company": "asdads",
   "position": "345345"
}

###

POST http://127.0.0.1:1337/api/v1/user/login
Content-Type: application/json

{
   "email":"test@mail.ru",
   "password": "5aaaaaaaa"
}



###

POST http://127.0.0.1:1337/api/v1/user/register/confirm
Content-Type: application/json

{
   "email": "test@mail.ru",
   "token": "2830bddec99554e38bedb641d953d5550"
}

###

GET http://127.0.0.1:1337/api/v1/user/details
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08


###

POST http://127.0.0.1:1337/api/v1/user/details
Content-Type: application/json
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08

{  
   "first_name": "Aleks_4",
   "last_name": "Star",
   "email": "test@mail.ru",
   "password": "5aaaaaaaa",
   "company": "apple",
   "position": "buyer"  
}

###

GET http://127.0.0.1:1337/api/v1/user/contact HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08

###

POST http://127.0.0.1:1337/api/v1/user/contact HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08
Content-Type: application/json

{
   "city": "M",
   "street": "Lesnaji",
   "phone": "87675454"
}

###

DELETE http://127.0.0.1:1337/api/v1/user/contact HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08
Content-Type: application/json

{
   "items": "1"
}


###

PUT http://127.0.0.1:1337/api/v1/user/contact HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08
Content-Type: application/json

{
   "id": "4",
   "city": "Samara"
}

###

POST http://127.0.0.1:1337/api/v1/user/password_reset HTTP/1.1
Content-Type: application/json

{
   "email":"elena.88@mail.ru"
}

###

###

POST http://127.0.0.1:1337/api/v1/user/password_reset/confirm
Content-Type: application/json

{
   "email":"elena.88@mail.ru",
   "password":"2aaaaaaaa3",
   "token":"6603cac8753fed8d7d5082a775de32a424a9a9ab"
}

###


POST http://127.0.0.1:1337/api/v1/partner/update
Authorization: Token d6cb4c30e071594acca758bad1edcbe13c63c7b9
Content-Type: application/json

{
   "url": "https://raw.githubusercontent.com/AnnSergeevn/python-final-diplom/master/data/shop1.yaml"
}

###

GET http://127.0.0.1:1337/api/v1/categories

###

GET http://127.0.0.1:1337/api/v1/shops

###

GET http://127.0.0.1:1337/api/v1/products HTTP/1.1
Content-Type: application/json

###

GET http://127.0.0.1:1337/api/v1/basket HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08

###

POST http://127.0.0.1:1337/api/v1/basket HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08

items=[
  {
    "product_info": 22,
    "quantity": 13
  },
  {
    "product_info": 15,
    "quantity": 12
  }
]


###

DELETE http://127.0.0.1:1337/api/v1/basket HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08

items=2

###

PUT http://127.0.0.1:1337/api/v1/basket HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08

items=[{ "id": 2, "quantity": 1} ]
###


###

GET http://127.0.0.1:1337/api/v1/order HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08


###
POST http://127.0.0.1:1337/api/v1/order HTTP/1.1
Authorization: Token fa1c6f5e89a60631b428cee94e58cfda4620bc08
Content-Type: application/json

{
"id": "1",
"contact": "1"}


###
GET http://127.0.0.1:1337/api/v1/partner/state HTTP/1.1
Authorization: Token d6cb4c30e071594acca758bad1edcbe13c63c7b9
Content-Type: application/x-www-form-urlencoded

   url = "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"

######

GET http://127.0.0.1:1337/api/v1/partner/orders HTTP/1.1
Authorization: Token d6cb4c30e071594acca758bad1edcbe13c63c7b9
Content-Type: application/x-www-form-urlencoded

   url = "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"


